# Generated by Django 4.0.5 on 2022-06-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0002_device_remove_siteuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
